// examples/react-router/customer-onboarding-journey/shell/src/components/TabContent.tsx
import { useSyncExternalStore } from "react";
import type { StoreApi } from "zustand/vanilla";
import type { ModuleDescriptor } from "@modular-react/core";
import { JourneyOutlet, ModuleTab } from "@modular-react/journeys";
import type { WorkspaceActions } from "@example-onboarding/app-shared";
import type { WorkspaceTabsState, Tab } from "../stores/workspace-tabs.js";

export interface TabContentProps {
  readonly tabsStore: StoreApi<WorkspaceTabsState>;
  readonly workspace: WorkspaceActions;
  readonly moduleDescriptors: Readonly<Record<string, ModuleDescriptor<any, any, any, any>>>;
}

function LoadingFallback() {
  return <div style={{ color: "#4a5568" }}>Loading journey…</div>;
}

export function TabContent({
  tabsStore,
  workspace,
  moduleDescriptors,
}: TabContentProps) {
  const state = useSyncExternalStore(tabsStore.subscribe, tabsStore.getState);

  if (state.activeTabId === null) return null;
  const tab = state.tabs.find((t) => t.tabId === state.activeTabId);
  if (!tab) return null;

  return (
    <main style={{ flex: 1, padding: "1.5rem", backgroundColor: "#f7fafc" }}>
      <TabBody tab={tab} workspace={workspace} moduleDescriptors={moduleDescriptors} />
    </main>
  );
}

function TabBody({
  tab,
  workspace,
  moduleDescriptors,
}: {
  readonly tab: Tab;
  readonly workspace: WorkspaceActions;
  readonly moduleDescriptors: Readonly<Record<string, ModuleDescriptor<any, any, any, any>>>;
}) {
  if (tab.kind === "journey") {
    // Runtime + module map come from the <JourneyProvider> mounted in main.tsx —
    // no prop threading needed.
    return (
      <JourneyOutlet
        instanceId={tab.instanceId}
        loadingFallback={<LoadingFallback />}
        onFinished={() => workspace.closeTab(tab.tabId)}
      />
    );
  }

  const mod = moduleDescriptors[tab.moduleId];
  if (!mod) {
    return <p style={{ color: "#c53030" }}>Module "{tab.moduleId}" is not registered.</p>;
  }
  return (
    <ModuleTab
      module={mod}
      entry={tab.entry}
      input={tab.input}
      tabId={tab.tabId}
      onExit={(ev) => {
        workspace.closeTab(tab.tabId);
        // `onModuleExit` wired on the provider also fires — see main.tsx.
        console.debug("[module exit]", ev);
      }}
    />
  );
}

// examples/vue/customer-onboarding-journey/shell/src/components/TabContent.vue
<script setup lang="ts">
import { computed, h } from "vue";
import { JourneyOutlet } from "@modular-vue/journeys";
import { workspace, workspaceTabs } from "../workspace.js";

const state = workspaceTabs.state;
const activeTab = computed(() =>
  state.activeTabId === null
    ? null
    : (state.tabs.find((t) => t.tabId === state.activeTabId) ?? null),
);

// `loadingFallback` accepts a VNode factory — rendered while a lazy step
// (e.g. billing/collect) resolves.
const loadingFallback = () => h("div", { style: { color: "#4a5568" } }, "Loading journey…");

function onFinished(): void {
  const tab = activeTab.value;
  if (tab) workspace.closeTab(tab.tabId);
}
</script>

<template>
  <main v-if="activeTab" :style="{ flex: 1, padding: '1.5rem', backgroundColor: '#f7fafc' }">
    <!--
      Runtime + module map come from the <JourneyProvider> threaded into the
      manifest's Providers stack (main.ts) — no prop threading needed. The
      outlet resolves the step component by id against the registered modules.
    -->
    <JourneyOutlet
      :instance-id="activeTab.instanceId"
      :loading-fallback="loadingFallback"
      :on-finished="onFinished"
    />
  </main>
</template>
